#Task 1

In [2]:
import numpy as np

original = np.random.rand(3,28,28)
original

 

array([[[0.04154391, 0.72881831, 0.26276356, ..., 0.04666558,
         0.37601884, 0.21223363],
        [0.31507284, 0.81258488, 0.54121415, ..., 0.09072081,
         0.35999026, 0.51410901],
        [0.85762381, 0.41943489, 0.54284086, ..., 0.45512212,
         0.5590604 , 0.06251807],
        ...,
        [0.92154148, 0.24364902, 0.69989967, ..., 0.23732193,
         0.15335157, 0.12325058],
        [0.63241947, 0.453881  , 0.82987356, ..., 0.74873736,
         0.5978746 , 0.32167678],
        [0.24346131, 0.40764375, 0.39134619, ..., 0.60207642,
         0.1421796 , 0.10673789]],

       [[0.12797936, 0.48338187, 0.95866106, ..., 0.22438023,
         0.01021494, 0.47260803],
        [0.07053358, 0.31769211, 0.01222954, ..., 0.83559734,
         0.30560109, 0.04083415],
        [0.07714289, 0.8189695 , 0.15225342, ..., 0.68071371,
         0.51760085, 0.7099583 ],
        ...,
        [0.18909038, 0.88271734, 0.90493953, ..., 0.81442491,
         0.03242436, 0.99099748],
        [0.4

In [ ]:
original.shape

(3, 28, 28)

In [3]:
flat = np.reshape(original,-1)
flat

array([0.04154391, 0.72881831, 0.26276356, ..., 0.86204607, 0.01682654,
       0.01071633])

In [ ]:
flat.shape

(2352,)

In [4]:
flat.flatten()

array([0.04154391, 0.72881831, 0.26276356, ..., 0.86204607, 0.01682654,
       0.01071633])

In [ ]:
flat.flatten().shape

(2352,)

#Task 2

In [5]:
#dimension of array
print('Number of dimension for original array:', original.ndim)
print('Number of dimension for flat array:', flat.ndim)

Number of dimension for original array: 3
Number of dimension for flat array: 1


In [6]:
#memory address
print('Memory address for original array:', original.data)
print('Memory address for flat array:', flat.data)

Memory address for original array: <memory at 0x7f4c5d4ffd50>
Memory address for flat array: <memory at 0x7f4c579e21f0>


In [ ]:
#shape
print('Shape for original array:', original.shape)
print('Shape for flat array:', flat.shape)

Shape for original array: (3, 28, 28)
Shape for flat array: (2352,)


In [ ]:
#data type
print('Data type for original array:', original.dtype)
print('Data type for flat array:', flat.dtype)

Data type for original array: float64
Data type for flat array: float64


#Task 3

In [7]:
negative_original = np.negative(original)
negative_original

array([[[-0.04154391, -0.72881831, -0.26276356, ..., -0.04666558,
         -0.37601884, -0.21223363],
        [-0.31507284, -0.81258488, -0.54121415, ..., -0.09072081,
         -0.35999026, -0.51410901],
        [-0.85762381, -0.41943489, -0.54284086, ..., -0.45512212,
         -0.5590604 , -0.06251807],
        ...,
        [-0.92154148, -0.24364902, -0.69989967, ..., -0.23732193,
         -0.15335157, -0.12325058],
        [-0.63241947, -0.453881  , -0.82987356, ..., -0.74873736,
         -0.5978746 , -0.32167678],
        [-0.24346131, -0.40764375, -0.39134619, ..., -0.60207642,
         -0.1421796 , -0.10673789]],

       [[-0.12797936, -0.48338187, -0.95866106, ..., -0.22438023,
         -0.01021494, -0.47260803],
        [-0.07053358, -0.31769211, -0.01222954, ..., -0.83559734,
         -0.30560109, -0.04083415],
        [-0.07714289, -0.8189695 , -0.15225342, ..., -0.68071371,
         -0.51760085, -0.7099583 ],
        ...,
        [-0.18909038, -0.88271734, -0.90493953, ..., -

In [8]:
original + negative_original

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

#Task 4 

In [ ]:
print(original[1,1,0:10])

[0.27087605 0.86977077 0.55255338 0.66089641 0.3009887  0.38700994
 0.9618377  0.87895565 0.50379611 0.68945564]


#Task 5

In [ ]:
print('Shape of blue matrix:', original[2].shape)
print('First three rows of blue matrix:', original[2,0:3,:])

Shape of blue matrix: (28, 28)
First three rows of blue matrix: [[0.91183745 0.0851353  0.8853412  0.29334466 0.17167225 0.17561578
  0.64671557 0.06957556 0.15825919 0.52248343 0.05835203 0.13607383
  0.78527398 0.68434927 0.18039988 0.36158197 0.5170935  0.51839875
  0.12510286 0.82599097 0.93376784 0.79686928 0.10045941 0.61615278
  0.28813358 0.86645843 0.13849368 0.01503232]
 [0.36203562 0.61718734 0.058413   0.13127112 0.28365303 0.49777331
  0.97679242 0.2452285  0.16470744 0.92009632 0.28460971 0.19631231
  0.33244108 0.18062388 0.87048435 0.53632226 0.13368286 0.63869654
  0.77236125 0.91244226 0.54805728 0.09950611 0.95632819 0.8824594
  0.63272625 0.22800895 0.46103239 0.3125756 ]
 [0.03769046 0.91226737 0.16196852 0.34017068 0.17749467 0.49956022
  0.4848078  0.20256702 0.63626165 0.82379352 0.14938491 0.77461718
  0.8121967  0.33023298 0.13438498 0.24996514 0.20673963 0.64415338
  0.22195998 0.3998536  0.90286687 0.53320679 0.73796445 0.14960635
  0.81275064 0.05604428 0.0

#Task 6

In [9]:
even = np.arange(0,100,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [16]:
even.shape
even = even.reshape(10,5)
#even
even.transpose()


array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98]])

#Task 7

In [14]:
for i in range(10):
  #print(sum(even[i]))
  mean = sum(even[i]) / len(even[i])
  print('Mean for row ', i, ':', mean)


for j in range(5):
    col_sum = 0
    for i in range(10):
      col_sum += even[i][j]
      col_mean = col_sum / 10
      
    print('Mean for column ', j, ':', col_mean)


Mean for row  0 : 4.0
Mean for row  1 : 14.0
Mean for row  2 : 24.0
Mean for row  3 : 34.0
Mean for row  4 : 44.0
Mean for row  5 : 54.0
Mean for row  6 : 64.0
Mean for row  7 : 74.0
Mean for row  8 : 84.0
Mean for row  9 : 94.0
Mean for column  0 : 45.0
Mean for column  1 : 47.0
Mean for column  2 : 49.0
Mean for column  3 : 51.0
Mean for column  4 : 53.0


#Task 8

We cannot create a 3x3 array of the first 50 even numbers, as the 3x3 can only fit 9 elements, which is much smaller than the 50 numbers.

Other possible m x n dimensions for the 50 numbers are
1) 2 x 25 or 25 x 2
2) 1 x 50 or 50 x 1
3) 5 x 10 or 10 x 5 (in Task 6)
